/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProtectedPlatformRouteImport } from './routes/_protected/platform'
import { Route as ProtectedPlatformTasksRouteImport } from './routes/_protected/platform.tasks'
import { Route as ProtectedPlatformTaskTaskIdRouteImport } from './routes/_protected/platform.task.$taskId'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedPlatformRoute = ProtectedPlatformRouteImport.update({
  id: '/_protected/platform',
  path: '/platform',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedPlatformTasksRoute = ProtectedPlatformTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => ProtectedPlatformRoute,
} as any)
const ProtectedPlatformTaskTaskIdRoute =
  ProtectedPlatformTaskTaskIdRouteImport.update({
    id: '/task/$taskId',
    path: '/task/$taskId',
    getParentRoute: () => ProtectedPlatformRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/platform': typeof ProtectedPlatformRouteWithChildren
  '/platform/tasks': typeof ProtectedPlatformTasksRoute
  '/platform/task/$taskId': typeof ProtectedPlatformTaskTaskIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/platform': typeof ProtectedPlatformRouteWithChildren
  '/platform/tasks': typeof ProtectedPlatformTasksRoute
  '/platform/task/$taskId': typeof ProtectedPlatformTaskTaskIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/_protected/platform': typeof ProtectedPlatformRouteWithChildren
  '/_protected/platform/tasks': typeof ProtectedPlatformTasksRoute
  '/_protected/platform/task/$taskId': typeof ProtectedPlatformTaskTaskIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/register'
    | '/platform'
    | '/platform/tasks'
    | '/platform/task/$taskId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/platform'
    | '/platform/tasks'
    | '/platform/task/$taskId'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/register'
    | '/_protected/platform'
    | '/_protected/platform/tasks'
    | '/_protected/platform/task/$taskId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  ProtectedPlatformRoute: typeof ProtectedPlatformRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/platform': {
      id: '/_protected/platform'
      path: '/platform'
      fullPath: '/platform'
      preLoaderRoute: typeof ProtectedPlatformRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/platform/tasks': {
      id: '/_protected/platform/tasks'
      path: '/tasks'
      fullPath: '/platform/tasks'
      preLoaderRoute: typeof ProtectedPlatformTasksRouteImport
      parentRoute: typeof ProtectedPlatformRoute
    }
    '/_protected/platform/task/$taskId': {
      id: '/_protected/platform/task/$taskId'
      path: '/task/$taskId'
      fullPath: '/platform/task/$taskId'
      preLoaderRoute: typeof ProtectedPlatformTaskTaskIdRouteImport
      parentRoute: typeof ProtectedPlatformRoute
    }
  }
}

interface ProtectedPlatformRouteChildren {
  ProtectedPlatformTasksRoute: typeof ProtectedPlatformTasksRoute
  ProtectedPlatformTaskTaskIdRoute: typeof ProtectedPlatformTaskTaskIdRoute
}

const ProtectedPlatformRouteChildren: ProtectedPlatformRouteChildren = {
  ProtectedPlatformTasksRoute: ProtectedPlatformTasksRoute,
  ProtectedPlatformTaskTaskIdRoute: ProtectedPlatformTaskTaskIdRoute,
}

const ProtectedPlatformRouteWithChildren =
  ProtectedPlatformRoute._addFileChildren(ProtectedPlatformRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  ProtectedPlatformRoute: ProtectedPlatformRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
